export default {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: 100,
    background: '#404040',
    fontSize: 60,
    fontWeight: 700,
    lineHeight: '100px',
    fontFamily: 'Rubik',
    textTransform: 'uppercase',
    letterSpacing: '10px',
    color: '#E5E5E5',
  },
  app: {
    background: '#E5E5E5',
    minHeight: 'calc(100vh - 180px)',
    padding: '160px 20px 20px 20px',
    textAlign: 'center',
    fontFamily: 'Roboto Mono',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayLink: {
    opacity: 0,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    zIndex: 1,
    cursor: 'pointer',
  },
  relative: {
    position: 'relative',
  },
  hello: {
    opacity: 0.35,
    margin: '50px 0 0 0',
  },
  userBar: {
    position: 'relative',
    height: 50,
    lineHeight: '50px',
    background: '#7F7F7F',
    color: '#CECECE',
    borderRadius: '10px 10px 0 0',
  },
  actionBar: {
    height: 50,
    lineHeight: '50px',
    background: 'rgba(250,250,250,0.45)',
    padding: '10px 0 0 0',
    borderRadius: '0 0 10px 10px',
  },
  profilePicture: {
    position: 'absolute',
    zIndex: 1,
    top: -20,
    right: -20,
    height: 80,
    width: 80,
    borderRadius: '50%',
    boxShadow: '0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23)',
  },
  tweetList: {
    position: 'relative',
    padding: 20,
    background: 'rgba(250,250,250,0.45)',
    height: 400,
    width: 300,
    textAlign: 'left',
    overflow: 'scroll',
  },
  tweet: {
    margin: '0 0 20px 10px',
  },
  tweetText: {
    fontStyle: 'italic',
  },
  tweetTimestamp: {
    opacity: 0.5,
  },
  refreshTweetsButton: {
    cursor: 'pointer',
    width: '50%',
    height: '100%',
    borderRadius: '0 0 0 10px',
    backgroundColor: '#BFBFBF',
    outline: 'none',
    border: '1px solid rgb(170,170,170)',
    color: '#7F7F7F',
  },
  logoutButton: {
    cursor: 'pointer',
    width: '50%',
    height: '100%',
    borderRadius: '0 0 10px 0',
    backgroundColor: '#BFBFBF',
    outline: 'none',
    border: '1px solid rgb(170,170,170)',
    borderLeft: 'none',
    color: '#7F7F7F',
  },
  newTweetBtn: {
    cursor: 'pointer',
    color: '#BFBFBF',
    width: 30,
    height: 30,
    lineHeight: '30px',
    background: 'white',
    fontSize: 40,
    padding: 10,
    borderRadius: '50%',
    position: 'absolute',
    bottom: 130,
    right: 10,
    zIndex: 1,
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0,0,0,0.85)',
    zIndex: 2,
  },
  closeOverlayBtn: {
    cursor: 'pointer',
    position: 'absolute',
    top: 0,
    right: 20,
    fontSize: 60,
    fontWeight: 700,
    lineHeight: '100px',
    fontFamily: 'Rubik',
    textTransform: 'uppercase',
    letterSpacing: '10px',
    color: '#E5E5E5',
  },
  newTweetTitle: {
    fontSize: 40,
    fontWeight: 700,
    lineHeight: '100px',
    fontFamily: 'Rubik',
    textTransform: 'uppercase',
    letterSpacing: '10px',
    color: '#E5E5E5',
  },
  newTweetInput: {
    padding: '0 20px',
    border: 'none',
    outline: 'none',
    height: 50,
    width: 300,
    borderRadius: '10px 0 0 10px',
  },
  tweetItBtn: {
    padding: '0 10px',
    background: '#BFBFBF',
    cursor: 'pointer',
    height: 50,
    borderRadius: '0 10px 10px 0',
  },
}
